### ISSUE TITLE
about error

### ISSUE THREAD

**Issue by leizhu1989** [talentAN/markdown2markdown-demo#1]
I build a md file in en folder, when I open zilliz in vscode ,it has a error "md2md error". why？  I have npm install

**Comment by leizhu1989** [comment]
大佬，我是在windows下验证的，在这个demo的目录下 npm install了，vscode打开这个demo目录，md2md是要通过右上角的zilliz按钮点击打开的吗，我点这个出现md2md error 。求大佬指教

**Comment by leizhu1989** [comment]
运行npm start报错了：
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> md2md-demo@1.0.0 start
> node index.js

=> Origin file D:\project\md2md-demo\doc_from\en\compose_fragment.md is edited.
=> Target File D:/project/md2md-demo/doc_to/en/compose_fragment.md is updated.


=> Origin file D:\project\md2md-demo\doc_from\en\Glossary.json is edited.
=> Origin file D:\project\md2md-demo\doc_from\en\kadun.md is edited.
=> Target File D:/project/md2md-demo/doc_to/en/kadun.md is updated.


=> Origin file D:\project\md2md-demo\doc_from\en\normal.md is edited.
=> Target File D:/project/md2md-demo/doc_to/en/normal.md is updated.


=> Origin file D:\project\md2md-demo\doc_from\en\test_fragment.md is edited.
=> Target File D:/project/md2md-demo/doc_to/en/test_fragment.md is updated.


=> Origin file D:\project\md2md-demo\doc_from\en\test_template.json is edited.
undefined:2
  "useTemplate": true,  // 必须
                        ^

SyntaxError: Unexpected token / in JSON at position 27
    at JSON.parse (<anonymous>)
    at parseJsonFile (D:\project\md2md-demo\node_modules\md2md\src\helpers\File.js:27:15)
    at _isTemplateJson (D:\project\md2md-demo\node_modules\md2md\src\helpers\File.js:209:19)
    at getFileType (D:\project\md2md-demo\node_modules\md2md\src\helpers\File.js:230:28)
    at FSWatcher.onFileAdd (D:\project\md2md-demo\node_modules\md2md\index.js:84:21)
    at FSWatcher.emit (node:events:527:28)
    at FSWatcher.emitWithAll (D:\project\md2md-demo\node_modules\chokidar\index.js:540:8)
    at FSWatcher._emit (D:\project\md2md-demo\node_modules\chokidar\index.js:632:8)
    at NodeFsHandler._handleFile (D:\project\md2md-demo\node_modules\chokidar\lib\nodefs-handler.js:400:14)
    at NodeFsHandler._addToNodeFs (D:\project\md2md-demo\node_modules\chokidar\lib\nodefs-handler.js:637:21)

Node.js v17.9.1

**Comment by leizhu1989** [comment]
上一个问题我把 必须删掉可以了。不过又有新的问题，求大佬指教：
=> Origin file D:\project\md2md-demo\doc_from\en\Variables.json is edited.
=> Origin file D:\project\md2md-demo\doc_from\en\fragments\compose.md is edited.
=> Origin file D:\project\md2md-demo\doc_from\en\fragments\head.md is edited.
=> Origin file D:\project\md2md-demo\doc_from\en\fragments\tail.md is edited.
=> Origin file D:\project\md2md-demo\doc_from\en\templates\example.md is edited.
=> Origin file D:\project\md2md-demo\doc_from\en\test-tab\all.md is edited.
D:\project\md2md-demo\node_modules\md2md\src\plugin\Tab.js:39
      const arrRelLink = link.split("/");
                              ^

TypeError: Cannot read properties of undefined (reading 'split')
    at D:\project\md2md-demo\node_modules\md2md\src\plugin\Tab.js:39:31
    at Array.map (<anonymous>)
    at parseTab (D:\project\md2md-demo\node_modules\md2md\src\plugin\Tab.js:37:6)
    at D:\project\md2md-demo\node_modules\md2md\index.js:77:15
    at Array.forEach (<anonymous>)
    at _customParse (D:\project\md2md-demo\node_modules\md2md\index.js:75:25)
    at FSWatcher.onFileAdd (D:\project\md2md-demo\node_modules\md2md\index.js:100:19)
    at FSWatcher.emit (node:events:527:28)
    at FSWatcher.emitWithAll (D:\project\md2md-demo\node_modules\chokidar\index.js:540:8)
    at FSWatcher._emit (D:\project\md2md-demo\node_modules\chokidar\index.js:632:8)

Node.js v17.9.1

**Comment by leizhu1989** [comment]
已经解决了
